#.travis.yml

language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install


script:
  - ng build --prod

after_success:
  - firebase deploy
